# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_GS101_MIPI_CSIS) += gs101-mipi-csis.o
obj-y += exynos-gsc/
obj-y += exynos4-is/
obj-y += s3c-camif/
obj-y += s5p-g2d/
obj-y += s5p-jpeg/
obj-y += s5p-mfc/
